name: Build
on: [push]

env:
  IMAGE: ghcr.io/dellelce/redis-base

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Mkit Redis 
        run: docker build -t $IMAGE .
      - name: Redis check version
        run: echo "REDIS_VERSION=$(docker run --rm $IMAGE  /app/redis/bin/redis-cli --version | awk ' { print $2 }' )" >> $GITHUB_ENV
      - name: Add tag & push
        run: docker tag $IMAGE $IMAGE:$REDIS_VERSION && docker push $IMAGE:$REDIS_VERSION && docker push $IMAGE
